import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { LanguageProvider } from "./context/LanguageContext";
import { ClerkProvider } from "@clerk/nextjs";
 

export const metadata: Metadata = {
  title: "Casa Cangalha",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className="min-h-screen flex flex-col"
       style={{
        backgroundColor: "#f0f0f0",
       }}
       >
        <LanguageProvider>
          <div className="fixed top-0 left-0 right-0 z-50">
            <Header />
          </div>
          <main className="flex-grow py-4 px-8 mt-8">
            {children}
          </main>
          <Footer />
        </LanguageProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}

// 65844A