import type { Metadata } from "next";
import "./globals.css";
import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";
import { LanguageProvider } from "./context/LanguageContext";
import { ClerkProvider } from "@clerk/nextjs";
 

export const metadata: Metadata = {
  title: "Casa Cangalha",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className="min-h-screen flex flex-col" >
        <LanguageProvider>
          <Header />
          <main className="flex-grow py-4 px-8">
            {children}
          </main>
          <Footer />
        </LanguageProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}

// 65844A